# Generated by Django 4.2.3 on 2023-08-12 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('rule', models.JSONField()),
                ('category', models.CharField(choices=[('%', 'Percentage'), ('real', 'Real Amount'), ('ship', 'Shipping Amount')], default=None, max_length=5)),
                ('image', models.FileField(blank=True, null=True, upload_to='../img/discounts/')),
            ],
            options={
                'db_table': 'discounts',
            },
        ),
        migrations.CreateModel(
            name='TrxAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('journey', 'Journey Types'), ('transaction', 'Transaction Types')], max_length=15)),
            ],
            options={
                'db_table': 'trx_attributes',
            },
        ),
        migrations.CreateModel(
            name='TrxHeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('estimation_date', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                ('discount_price', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trx_cities', related_query_name='trx_city', to='app_user.areas', verbose_name='City Key')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trx_countries', related_query_name='trx_country', to='app_user.areas', verbose_name='Country Key')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_transaction.discounts', verbose_name='Discount Key')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trx_provinces', related_query_name='trx_province', to='app_user.areas', verbose_name='Province Key')),
                ('trx_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_transaction.trxattributes', verbose_name='Transaction Type Key')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User Key')),
            ],
            options={
                'db_table': 'trx_headers',
            },
        ),
        migrations.CreateModel(
            name='TrxLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField(default=0)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_transaction.discounts', verbose_name='Discount Key')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_transaction.trxheaders', verbose_name='Transaction Header Key')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.products', verbose_name='Product Key')),
            ],
            options={
                'db_table': 'trx_lines',
            },
        ),
        migrations.CreateModel(
            name='Wishlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.products', verbose_name='Product Key')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User Key')),
            ],
            options={
                'db_table': 'wishlists',
            },
        ),
        migrations.CreateModel(
            name='TrxReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('review', models.IntegerField()),
                ('comment', models.TextField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_transaction.trxlines', verbose_name='Transaction Line Key')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User Key')),
            ],
            options={
                'db_table': 'trx_reviews',
            },
        ),
        migrations.CreateModel(
            name='TrxJourneys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_transaction.trxheaders', verbose_name='Transcation Header Key')),
                ('journey_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_transaction.trxattributes', verbose_name='Journey Key')),
            ],
            options={
                'db_table': 'trx_journeys',
            },
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.products', verbose_name='Product Key')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User Key')),
                ('wishlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_transaction.wishlists', verbose_name='Wishlist Key')),
            ],
            options={
                'db_table': 'carts',
            },
        ),
    ]
