# Generated by Django 4.2.3 on 2023-08-21 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transaction', '0003_trxheaders_trx_number_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxlines',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='header_key', to='app_transaction.trxheaders', verbose_name='Transaction Header Key'),
        ),
    ]
