# Generated by Django 4.2.3 on 2023-08-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transaction', '0004_alter_trxlines_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='trxheaders',
            name='city_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trxheaders',
            name='country_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trxheaders',
            name='province_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trxheaders',
            name='city',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trxheaders',
            name='country',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trxheaders',
            name='province',
            field=models.IntegerField(default=0),
        ),
    ]
