# Generated by Django 4.2.3 on 2023-08-22 02:17

import app_transaction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transaction', '0006_rename_city_trxheaders_city_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trxheaders',
            name='estimation_date',
        ),
        migrations.RemoveField(
            model_name='trxheaders',
            name='trx_type',
        ),
        migrations.AddField(
            model_name='trxjourneys',
            name='estimation_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='trxheaders',
            name='trx_number',
            field=models.CharField(default=app_transaction.models.TrxHeaders.auto_trx_number, max_length=20),
        ),
        migrations.AlterField(
            model_name='trxjourneys',
            name='journey_type',
            field=models.CharField(choices=[('WAITING_CONFIRMATION', 'Waiting Confirmation By Seller'), ('CONFIRMED', 'Order Confirmed By Seller'), ('PROCESSED', 'Order Processed'), ('PICK_BY_SHIPPER', 'Order Pick By Shipper'), ('ON_SHIPPING', 'On The Way'), ('ORDER_SENDED', 'Order Already Sended To Customer'), ('SUCCESS', 'The order has been received well by the user'), ('FAILED', 'The order is returned to seller')], max_length=50),
        ),
        migrations.DeleteModel(
            name='TrxAttributes',
        ),
    ]
