# Generated by Django 4.2.3 on 2023-08-22 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transaction', '0007_remove_trxheaders_estimation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxlines',
            name='cart',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_transaction.carts', verbose_name='Cart Key'),
        ),
    ]
