# Generated by Django 4.2.3 on 2023-08-22 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transaction', '0009_alter_trxlines_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxlines',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trx_header_keys', to='app_transaction.trxheaders', verbose_name='Transaction Header Key'),
        ),
    ]
