# Generated by Django 4.2.3 on 2023-09-04 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0004_alter_productinventories_table'),
        ('app_transaction', '0014_alter_carts_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.products', verbose_name='Product Key'),
        ),
    ]
