# Generated by Django 4.2.3 on 2023-09-04 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transaction', '0015_alter_carts_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='wishlist',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_transaction.wishlists', verbose_name='Wishlist Key'),
        ),
    ]
