# Generated by Django 4.2.3 on 2023-09-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transaction', '0016_alter_carts_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trxheaders',
            name='country_id',
        ),
        migrations.AddField(
            model_name='trxheaders',
            name='postal_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='trxheaders',
            name='country_name',
            field=models.CharField(default='indonesia', max_length=100),
        ),
    ]
