# Generated by Django 4.2.3 on 2023-09-05 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transaction', '0019_alter_trxheaders_estimation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxheaders',
            name='estimation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
