# Generated by Django 4.2.3 on 2023-08-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transaction', '0005_trxheaders_city_name_trxheaders_country_name_and_more'),
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradresses',
            name='city_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='useradresses',
            name='country_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='useradresses',
            name='province_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='city_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='country_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='province_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='useradresses',
            name='city',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useradresses',
            name='country',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useradresses',
            name='province',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='city',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='country',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='province',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Areas',
        ),
    ]
