# Generated by Django 4.2.3 on 2023-09-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_rename_city_useradresses_city_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradresses',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='email',
        ),
        migrations.AddField(
            model_name='useradresses',
            name='tag',
            field=models.CharField(default='', max_length=50),
        ),
    ]
