# Generated by Django 4.2.3 on 2023-09-08 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_user', '0004_remove_useradresses_country_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBalanceHistories',
            new_name='UserBalances',
        ),
        migrations.AddField(
            model_name='useradresses',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User Key'),
        ),
        migrations.AlterModelTable(
            name='userbalances',
            table='user_balances',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
