# Generated by Django 4.2.3 on 2023-09-11 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_user', '0005_rename_userbalancehistories_userbalances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradresses',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_address_key', to=settings.AUTH_USER_MODEL, verbose_name='User Key'),
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('u', 'Unknown')], default='u', max_length=10)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User Key')),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
