# Generated by Django 4.2.3 on 2023-09-11 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_user', '0006_alter_useradresses_user_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='phone',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_details_key', to=settings.AUTH_USER_MODEL, verbose_name='User Key'),
        ),
    ]
