# Generated by Django 4.2.3 on 2023-08-28 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0002_remove_products_price_remove_products_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('size', models.IntegerField()),
                ('color', models.CharField(max_length=15)),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inv_product_keys', to='app_product.products', verbose_name='Product Key')),
            ],
            options={
                'db_table': 'product_inventory',
            },
        ),
        migrations.DeleteModel(
            name='ProductInventory',
        ),
    ]
